Repository m-lab/ndt-server, pull requests merged in 2018-12, with the labels that each got.

#41 Refactor ndt-server into a small main and a large library
  legacy/README.md
  legacy/c2s/c2s.go
  legacy/metrics/metrics.go
  legacy/protocol/protocol.go
  legacy/s2c/s2c.go
  legacy/tcplistener/tcplistener.go
  legacy/testresponder/testresponder.go
  legacy/testrunner.go
  ndt-server.go
  ndt-server_test.go
Labels: 2, P1, Sprint 22

#39 Fix BBR handshake and guarantee timely measurements
  html/libndt7.js
  html/ndt7.html
  legacy/tcplistener/tcplistener.go
  legacy/testresponder/testresponder.go
  ndt-server.go
  ndt7/client.go
  ndt7/resultsfile.go
  ndt7/server.go
  ndt7/spec.go
  spec/ndt7-protocol.md
Labels: bug, enhancement

#45 Refactor to increase code velocity
  fdcache/fdcache.go
  legacy/c2s/c2s.go
  legacy/metrics/metrics.go
  legacy/s2c/s2c.go
  legacy/testresponder/testresponder.go
  logging/logging.go
  ndt-server.go
  ndt-server_test.go
  ndt7/client.go
  ndt7/model/appinfo.go
  ndt7/model/bbrinfo.go
  ndt7/model/measurement.go
  ndt7/model/tcpinfo.go
  ndt7/server/download/download.go
  ndt7/server/results/file.go
  ndt7/server/results/metadata.go
  ndt7/spec.go
  ndt7/spec/spec.go
  tcpinfox/tcpinfox.go
  tcpinfox/tcpinfox_linux.go
  tcpinfox/tcpinfox_stub.go
  version/version.go
Labels: enhancement
