Repository m-lab/ndt-server, pull requests merged in 2019-03, with the labels that each got.

#52 The server now speaks non-ws NDT with JSON messages.
  TestDockerfile
  legacy/c2s/c2s.go
  legacy/legacy.go
  legacy/metrics/metrics.go
  legacy/protocol/protocol.go
  legacy/protocol/protocol_test.go
  legacy/s2c/s2c.go
  legacy/testresponder/testresponder.go
  legacy/testrunner.go
  metrics/metrics.go
  ndt-server.go
  ndt-server_test.go
  test.sh
Labels: 2019, 8, P0, P1, Sprint 23, Sprint 4

#67 Eliminate "ndt-cloud"
  TestDockerfile
  cmd/ndt-client/main.go
  ndt-server_test.go
  ndt7/server/listener/listener.go
Labels: 1, 2019, Sprint 5

#68 bbr: reimplement getting stats in pure go
  bbr/bbr.go
  bbr/bbr_linux.c
  bbr/bbr_linux.go
  bbr/bbr_linux.h
  ndt7/server/download/download.go
Labels: enhancement

#71 spec: use int64, allow counter-flow messages
  bbr/bbr_linux.go
  ndt7/client.go
  ndt7/model/appinfo.go
  ndt7/model/bbrinfo.go
  spec/ndt7-protocol.md
Labels: enhancement

#73 Measure MinRTT.
  legacy/c2s/c2s.go
  legacy/protocol/protocol.go
  legacy/protocol/protocol_test.go
  legacy/s2c/s2c.go
  legacy/testresponder/testresponder.go
  legacy/web100/web100.go
Labels: 2, 2019, Sprint 5

#76 fix(ndt-server.go): make ndt7 work again
  ndt-server.go
Labels: bug

#80 Make sure we build a fully static binary
  Dockerfile
  build.sh
Labels: bug

#81 ndt7/s/r/file.go: no colons in file names
  ndt7/server/results/file.go
Labels: bug

#88 ndt-server.go: forward -datadir to ndt7
  ndt-server.go
Labels: bug
